/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sossim;

import static sossim.Library.*;


public class FrameAspects extends javax.swing.JPanel {

    SOSSim sos = new SOSSim();
    Library lib = new Library();
    
    /**
     * Creates new form MainFrrame
     */
    public FrameAspects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        returnbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        debugToggle = new javax.swing.JToggleButton();
        hVelIn = new javax.swing.JTextField();
        vVelIn = new javax.swing.JTextField();
        gravityIn = new javax.swing.JTextField();
        panely = new javax.swing.JScrollBar();
        panelx = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bgSelector = new javax.swing.JComboBox<>();

        jButton2.setText("jButton2");

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        returnbtn.setText("Return");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });

        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        debugToggle.setText("Debug");
        debugToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugToggleActionPerformed(evt);
            }
        });

        hVelIn.setText("4");
        hVelIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hVelInActionPerformed(evt);
            }
        });

        vVelIn.setText("3");
        vVelIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vVelInActionPerformed(evt);
            }
        });

        gravityIn.setText("1");
        gravityIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravityInActionPerformed(evt);
            }
        });

        panely.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                panelyAdjustmentValueChanged(evt);
            }
        });

        panelx.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        panelx.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                panelxAdjustmentValueChanged(evt);
            }
        });

        jLabel1.setText("gravity:");

        jLabel2.setText("H vel:");

        jLabel3.setText("V vel:");

        bgSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grassy", "overgrown", "temple", "forest" }));
        bgSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hVelIn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vVelIn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gravityIn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelx, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(panely, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(debugToggle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bgSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnbtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(hVelIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panelx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(vVelIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gravityIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panely, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returnbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debugToggle)
                    .addComponent(exitbtn)
                    .addComponent(bgSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hVelInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hVelInActionPerformed
        hVel = Integer.parseInt(hVelIn.getText());
    }//GEN-LAST:event_hVelInActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        SOSSim.menu.setVisible(false);
    }//GEN-LAST:event_returnbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void gravityInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravityInActionPerformed
        g = Integer.parseInt(gravityIn.getText());
    }//GEN-LAST:event_gravityInActionPerformed

    private void debugToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugToggleActionPerformed
        //shortcut?
        if (debug) {debug=false;} else {debug=true;}
    }//GEN-LAST:event_debugToggleActionPerformed

    private void panelyAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_panelyAdjustmentValueChanged
        panel[0][1] = panely.getValue()*8;
        lib.print(panely.getValue());
        lib.print(panely.getValue()*8 + "\n");
    }//GEN-LAST:event_panelyAdjustmentValueChanged

    private void panelxAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_panelxAdjustmentValueChanged
        panel[0][0] = panelx.getValue()*8;
        lib.print(panelx.getValue());
        lib.print(panelx.getValue()*8 + "\n");
    }//GEN-LAST:event_panelxAdjustmentValueChanged

    private void vVelInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vVelInActionPerformed
        vVel = Integer.parseInt(vVelIn.getText());
    }//GEN-LAST:event_vVelInActionPerformed

    private void bgSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgSelectorActionPerformed
        if (String.valueOf(bgSelector.getSelectedItem()) == "grassy") {
            activeBg = grassyBg;
            sos.frame.setSize(1152, 864);
            sos.frame.setLocationRelativeTo(null);
            sideR = 1110;
            setBg();
        } else if (String.valueOf(bgSelector.getSelectedItem()) == "overgrown") {
            activeBg = overgrownBg;
            sos.frame.setSize(1920, 1080);
            sos.frame.setLocationRelativeTo(null);
            sideR = 1396;
            setBg();
        } else if (String.valueOf(bgSelector.getSelectedItem()) == "temple") {
            activeBg = templeBg;
            sos.frame.setSize(1920, 1200);
            sos.frame.setLocationRelativeTo(null);
            sideR = 1396;
            setBg();
        } else if (String.valueOf(bgSelector.getSelectedItem()) == "forest") {
            activeBg = forestBg;
            sos.frame.setSize(1920, 1080);
            sos.frame.setLocationRelativeTo(null);
            sideR = 1396;
            setBg();
        }
    }//GEN-LAST:event_bgSelectorActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bgSelector;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton debugToggle;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField gravityIn;
    private javax.swing.JTextField hVelIn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar panelx;
    private javax.swing.JScrollBar panely;
    private javax.swing.JButton returnbtn;
    private javax.swing.JTextField vVelIn;
    // End of variables declaration//GEN-END:variables
}
